---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: sooljari
network.host: 0.0.0.0
node.name: single-node

xpack.security.enabled: true